newrelic:
  build: .
  privileged: true
  environment:
    - NEW_RELIC_LICENSE_KEY=<YOUR-KEY>
  volumes:
#    - '/proc:/proc'
    - '/var/run/docker.sock:/var/run/docker.sock'
    - '/dev:/dev'
    - '/sys:/sys'

